### ISSUE TITLE
Doorbot2 is not responding to fobs

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/somebody-should#1139]
Screen is up, fobs are being read (red light shows) but door doesn't open.

**Comment by johnmckerrell** [comment]
The log cards screen wasn't running, reboot fixed things.

**Comment by amcewen** [comment]
Failed again today.  Pi seems up okay but the log cards screen isn't running.

**Comment by amcewen** [comment]
Have fixed the bug that meant the `visits.log` wasn't being written to (since the Slack integration got added), in commit https://github.com/DoESLiverpool/logcards/commit/fc8a70f2e1834a8e86167352b0b10024a05bc92f (not fully deployed it yet, but doorbot2 has a manually applied version), but I don't think that's what was causing the issue.

I've modded `/lib/systemd/system/logcards.service` to add a `-L` parameter to screen, so it's logging its output to `/home/pi/logcards/screenlog.0`.  That should let us see what's causing `screen` to exit if/when it happens again.  We should remove that once we've worked out the issue...

**Comment by johnmckerrell** [comment]
```
/var/lib/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``': Cannot allocate memory - echo 0 > /sys/class/gpio/gpio25/value (Errno::ENOMEM)
        from /var/lib/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
        from logcards.rb:149:in `setDoorState'
        from logcards.rb:434:in `rescue in <main>'
        from logcards.rb:213:in `<main>'
```

So it seems like it's running out of memory, seems a bit surprising, possibly something isn't being cleaned up when we're spawning the process to open the door. We should perhaps just write to the device to open the door from within ruby instead rather than spawning a shell.

**Comment by johnmckerrell** [comment]
Interestingly soon after a reboot (around the time of the last comment) `free -m` was reporting:
```
              total        used        free      shared  buff/cache   available
Mem:            926         158         438          12         328         703
Swap:            99           0          99
```

But now we get:
```
              total        used        free      shared  buff/cache   available
Mem:            926         232         358          12         334         629
Swap:            99           0          99
```

So it does seem like you can see the memory being used up. Again not really sure why it has changed.

I've just stopped the screen and the memory did drop but only to 200M, restarted it now and we're on:
```
              total        used        free      shared  buff/cache   available
Mem:            926         230         360          12         335         631
Swap:            99           0          99
```

**Comment by johnmckerrell** [comment]
```
              total        used        free      shared  buff/cache   available
Mem:            926         840          26           1          58          35
Swap:            99          98           1
```

**Comment by johnmckerrell** [comment]
Down again, ran out of memory. To be honest it's more likely to be the web browser so I've killed that and we'll see if it lasts better, I'll try to check later. Hm.. although we currently install a very specific version of kweb, so that won't have changed, it would be more likely an issue in X (or it could be the ruby as I originally thought). Killing kweb should give us an indication anyway.

**Comment by johnmckerrell** [comment]
Yeah, seems to be kweb, or something around the screen, as we're only using an additional 10M in a few hours (and in fact it dropped by 1M in the past ten minutes). From this earlier:
```
              total        used        free      shared  buff/cache   available
Mem:            926         118         563          12         243         744
Swap:            99           0          99
```
To this now:
```
              total        used        free      shared  buff/cache   available
Mem:            926         127         548          12         249         735
Swap:            99           0          99
```

**Comment by johnmckerrell** [comment]
I've installed surf and am running it manually, will see if this helps before updating the setup scripts.

**Comment by johnmckerrell** [comment]
```
              total        used        free      shared  buff/cache   available
Mem:            926         193         495          12         237         670
Swap:            99           0          99
```

**Comment by johnmckerrell** [comment]
Does seem like it's going up:
```
              total        used        free      shared  buff/cache   available
Mem:            926         325         361          12         239         537
Swap:            99           0          99
```

**Comment by johnmckerrell** [comment]
Went off again, same error message as previously:
```
/var/lib/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``': Cannot allocate memory - echo 0 > /sys/class/gpio/gpio25/value (Errno::ENOMEM)^M
        from /var/lib/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'^M
        from logcards.rb:149:in `setDoorState'^M
        from logcards.rb:434:in `rescue in <main>'^M
        from logcards.rb:213:in `<main>'^M
```

**Comment by johnmckerrell** [comment]
I've had a test install running on my desk for a few days, probably since Tuesday. Although the browser memory has gone quite large it was still running basically fine until today when the ruby process quit with the same problem about not being able to allocate memory. I ran the script again and it is working fine without a reboot or touching the browser which leads me to believe it's actually the ruby script that has the memory leak. Unfortately as the ruby script had crashed I couldn't see its memory use so I'm running it again keeping a closer eye on that. It's using backticks to perform the "door open" action so that's an easy fix but I want to get the crash again before changing anything.

**Comment by johnmckerrell** [comment]
I've now deployed the latest log cards to doorbot2 https://github.com/DoESLiverpool/logcards/pull/11

It's also running the surf web browser and I've run an `apt dist-upgrade` now.

I'll leave this issue open for 7 days or so to make sure this continues working.

**Comment by amcewen** [comment]
Hate to break it to you, but it's not working :-(

Pi is still up, `surf` is using 85% of the memory.  `screen` seems to be running still - I thought it had hung and so hit `Ctrl-C`, which interrupted wherever it was and it restarted and seems to be working again now.

It did dump a load of lines like this before the "Welcome to Doorbot" message though:
> Oops #<Errno::ENOMEM: Cannot allocate memory - mount | grep /media/Kindle>

`surf` has dropped to 11.2% of memory now though (I didn't do anything to that, which is strange)

**Comment by ajlennon** [comment]
Doesn't respond to hand implants either :-(

**Comment by johnmckerrell** [comment]
I've put a new version onto doorbot2, this one has removed everything to do with kindle, slack and any audio. You can also send a signal to it to get some information from the garbage collector and then run a garbage collection. If there's issues it might be interesting to send the signal before doing anything else:
```
kill -USR2 <process-id>
```

**Comment by johnmckerrell** [comment]
```
Oops #<Errno::ENOMEM: Cannot allocate memory - ./rcapp1>
```
Forgot to try killing it first but that's very interesting nonetheless! Annoyingly quick though. I'll kill the browser now, someone might want to check it's working ok now!
